<html>

<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <link rel="stylesheet" href="css/profile.css">
</head>

<body>
  <div class="container animated fadeIn">
    <div class="avatar">
      <img src="<?= $_SESSION['avatar'] ?>" class="avatar" alt="avatar">
      <h4>Vítejte zpět:</h4>
      <h1>
        <?= $_SESSION['username'] ?>
      </h1>
      <h6>
        <?= $_SESSION['accountType'] ?>
      </h6>
      <hr>
    </div>
    <div>
      <div class="alert alert-error"><?= $_SESSION['message'] ?></div>
      <div class="legend">
        <h6>Legenda</h6>
        <i class="fa fa-fw fa-book-reader"></i> Přidělit/Odstranit uživateli status recenzenta<br>
        <i class="fa fa-fw fa-upload"></i> Změnit status publikace článku<br>
        <i class="fa fa-fw fa-file-download"></i> Stáhnout pdf dokument<br>
        <i class="fa fa-fw fa-trash-alt"></i> Odstranit příspěvek/uživatele<br><br>
      </div>
      <table class="table-responsive-sm table table-striped">
        <thead class="thead-dark">
        <th class="heading" colspan="5"><h4>Seznam uživatelů</h4></th>
        <tr>
          <th>Avatar</th>
          <th>Uživatelské jméno</th>
          <th>Email</th>
          <th>Recenzent</th>
          <th>Akce</th>
        </tr>
      </thead>
        <tr>
          <?php foreach ($users as $user) : ?>
          <td><img src="<?= $user['avatar'] ?>"></img></td>
          <td><?= $user['username'] ?></td>
          <td><?= $user['email'] ?></td>
          <td><?= $user['reviewer'] ?></td>
          <td>
            <form action="/profile" method="post">
              <input type="hidden" name="user_id" value="<?= $user['id'] ?>">
              <button type = "submit" name="promote" title="Přidělit/Odstranit uživateli status recenzenta"><i class="fa fa-fw fa-book-reader"></i></button>
              <button type = "submit" name="deleteUser" title="Odstranit uživatele"><i class="fa fa-fw fa-trash-alt"></i></button>
            </form>
          </td>
        </tr>
      <?php endforeach ?>
      </table>

      <table class="table <?= $showArticles ?> table-responsive-sm">
        <thead class="thead-dark">
        <th class="heading" colspan="5"><h4>Seznam příspěvků</h4></th>
        <tr>
          <th>Název</th>
          <th>Autoři</th>
          <th>Recenze</th>
          <th>Publikováno</th>
          <th>Akce</th>
        </tr>
        </thead>
        <tr>
          <?php foreach ($articles as $article) : ?>
          <td><?= $article['title'] ?></td>
          <td><?= $article['authors'] ?></td>
          <td></td>
          <td><?= $article['published'] ?></td>
          <td>
            <form action="/profile" method="post">
              <input type="hidden" name="article_id" value="<?= $article['id'] ?>">
              <button type = "submit" name="publish" title="Změnit status publikace článku"><i class="fa fa-fw fa-upload"></i></button>
              <a href="<?= $article['pdf'] ?>" title="Stáhnout pdf dokument"><i class="fa fa-fw fa-file-download"></i></a>
              <button type = "submit" name="deleteArticle" title="Odstranit příspěvek"><i class="fa fa-fw fa-trash-alt"></i></button>
            </form>
          </td>
        </tr>
      <?php endforeach ?>
      </table>
      <hr>
      <form action="/profile" method="post">
        <a href=/profile?newArticle class="btn btn-success">Vložit článek</a>
        <button class="btn btn-primary" type="submit" name="logout">Odhlásit se</button>
        <button class="btn btn-danger" type="submit" name="deleteACC">Zrušit účet</button>
      </form>
    </div>
  </div>
</body>

</html>
