     <link rel="stylesheet" href="css/login.css">

     <div class="container">
       <div class="col-xl-4">
       <form class="form-signin" method="post" action="/login">
         <h2 class="form-signin-heading">Vítejte zpátky</h2>
         <div class="alert alert-error"><?= $_SESSION['message'] ?></div>
         <a href="/landing">< Zpět</a>
         <input type="email" name="email" class="inputBox" id="email" required>
         <label for="email" class="inputBox">Email</label>
         <input type="password" name="password" class="inputBox" id="password" required>
         <label for="password" class="inputBox">Heslo</label><br>
         Ještě nemáte účet? <a href="/register">Registrovat</a>
         <button class="btn btn-lg btn-primary btn-block" type="submit">Přihlásit se</button>
       </form>
     </div>
     </div>
