<html lang="en">
   <head>
     <link rel="stylesheet" href="css/login.css">
   </head>
   <body>
     <div class="container">
       <form class="form-signin" method="post" action="/login">
         <h2 class="form-signin-heading">Vítejte zpátky</h2>
         <a href="/landing">< Zpět</a>
         <div class="alert alert-error"><?= $_SESSION['message'] ?></div>
         <label for="inputEmail" class="sr-only">Email</label>
         <input type="email" name="email" class="form-control" placeholder="Email" required="" autofocus="">
         <label for="inputPassword" class="sr-only">Heslo</label>
         <input type="password" name="password" class="form-control" placeholder="Heslo" required="">
         <div class="checkbox">
           <label>
             <input type="checkbox" value="remember-me"> Zapamatovat
           </label>
         </div>
          <a href="forgot.php">Zapomněli jste heslo?</a><br>
         Ještě nemáte účet? <a href="/register">Registrovat</a>
         <button class="btn btn-lg btn-primary btn-block" type="submit">Přihlásit se</button>
       </form>
     </div>
   </body>
 </html>
