<!DOCTYPE html>
 <html>
   <head>
     <base href="/localhost" />
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="x-ua-compatible" content="ie=edge">
     <title><?= $title ?></title>
     <meta name="description" content="<?= $description ?>">
     <meta name="keywords" content="<?= $keywords ?>">

    <!-- CSS  -->
     <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
     <link rel="stylesheet" href="css/master.css">

   </head>
   <body>

    <div id="wrapper">
      <!-- Sidebar -->
    <div id="sidebar-wrapper">
      <nav class="logged-<?= $_SESSION['logged_in']?>">
        <div class="profile">
          <img src="<?= $_SESSION['avatar']?>" alt="avatar">
          <h4><a href="/profile"><?= $_SESSION['username'] ?></a></h4>
          <h6><?= $_SESSION['accountType'] ?></h6>
          <a href="/profile"><i class="fas fa-user"></i> Profil</a>
          <a href="/profile?newArticle"><i class="fas fa-pen"></i> Nový článek</a>
          <a href="/logout"><i class="fas fa-sign-out-alt"></i> Odhlásit se</a>
          <hr>
        </div>
        <a href="/landing#"><i class="fa fa-fw fa-home"></i> Domů</a>
        <a href="/articles"><i class="fas fa-newspaper"></i> Články</a>
        <a href="/about"><i class="fas fa-book-open"></i> O Konferenci</a>
      </nav>
    </div>



      <div id="page-content-wrapper">
              <div id="menu-toggle" onclick="toggleMenu(this)">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
              </div>
              <div class="container-fluid main-content">
                <?php $this->controler->getView(); ?>
            </div>
          </div>

    </div>

     <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


     <!-- Menu script -->
     <script>
       $("#menu-toggle").click( function (e) {
         e.preventDefault();
         $("#wrapper").toggleClass("menuDisplayed");
       });

       function toggleMenu(x) {
        x.classList.toggle("change");
    }
     </script>

   </body>
 </html>
