  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <link rel="stylesheet" href="css/profile.css">

  <div class="container animated fadeIn">

    <!-- PROFIL -->
    <div class="avatar">
      <img src="<?= $_SESSION['avatar'] ?>" class="avatar" alt="avatar">
      <h4>Vítejte zpět:</h4>
      <h1>
        <?= $_SESSION['username'] ?>
      </h1>
      <h6>
        <?= $_SESSION['accountType'] ?>
      </h6>
      <hr>
    </div>
    <div>
      <!--  MENU  -->
      <form action="/profile" method="post">
        <a href=/profile?newArticle class="btn btn-success">Vložit článek</a>
        <button class="btn btn-primary" type="submit" name="logout">Odhlásit se</button>
        <button class="btn btn-danger" type="submit" name="deleteACC">Zrušit účet</button>
      </form>
      <hr>

      <!-- INFO BOX -->
      <div class="alert alert-success"><?= $_SESSION['message'] ?></div>

      <!-- LEGENDA -->
      <div class="legend">
        <h6>Legenda</h6>
        <i class="fa fa-fw fa-file-download"></i> Stáhnout pdf dokument<br>
        <i class="fa fa-fw fa-trash-alt"></i> Odstranit příspěvek<br><br>
      </div>

      <!-- TABULKY -->
      <table class="table <?= $showArticles ?> table-responsive-sm">
        <thead class="thead-dark">
          <th class="heading" colspan="4">
            <h4>Seznam příspěvků</h4>
          </th>
          <tr>
            <th>Název</th>
            <th>Autoři</th>
            <th>Stav</th>
            <th>Akce</th>
          </tr>
        </thead>
        <tr>
          <?php foreach ($articles as $article) : ?>
          <td>
            <?= htmlentities($article['title']) ?>
          </td>
          <td>
            <?= htmlentities($article['authors']) ?>
          </td>
          <td>
            <?= $article['state'] ?>
          </td>
          <td>
            <form action="/profile" method="post">
              <input type="hidden" name="article_id" value="<?= $article['id'] ?>">
              <a href="<?= $article['pdf'] ?>" title="Stáhnout pdf dokument"><i class="fa fa-fw fa-file-download"></i></a>
              <button type="submit" name="deleteArticle" title="Odstranit příspěvek"><i class="fa fa-fw fa-trash-alt"></i></button>
            </form>
          </td>
        </tr>
        <?php endforeach ?>
      </table>
    </div>
  </div>
