<html>

<head>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css">
  <link rel="stylesheet" href="css/profile.css">
</head>

<body>
  <div class="container animated fadeIn">
    <div class="avatar">
      <img src="<?= $_SESSION['avatar'] ?>" class="avatar" alt="avatar">
      <h4>Vítejte zpět:</h4>
      <h1>
        <?= $_SESSION['username'] ?>
      </h1>
      <h6>
        <?= $_SESSION['accountType'] ?>
      </h6>
      <hr>
    </div>
    <div>
      <div class="alert alert-error"><?= $_SESSION['message'] ?></div>
      <div class="legend">
        <h6>Legenda</h6>
        <i class="fa fa-fw fa-file-download"></i> Stáhnout pdf dokument<br>
        <i class="fa fa-fw fa-upload"></i> Změnit status publikace recenze<br>
        <i class="fa fa-fw fa-edit"></i> Editovat recenzi<br>
        <i class="fa fa-fw fa-trash-alt"></i> Odstranit příspěvek/recenzi<br><br>
      </div>
      <table class="table <?= $showArticles ?> table-responsive-sm">
        <thead class="thead-dark">
        <th class="heading" colspan="3"><h4>Seznam příspěvků</h4></th>
        <tr>
          <th>Název</th>
          <th>Autoři</th>
          <th>Akce</th>
        </tr>
        </thead>
        <tr>
          <?php foreach ($articles as $article) : ?>
          <td><?= $article['title'] ?></td>
          <td><?= $article['authors'] ?></td>
          <td>
            <form action="/profile" method="post">
            <input type="hidden" name="article_id" value="<?= $article['id'] ?>">
            <a href="<?= $article['pdf'] ?>" title="Stáhnout pdf dokument"><i class="fa fa-fw fa-file-download"></i></a>
            <button type = "submit" name="deleteArticle" title="Odstranit příspěvek"><i class="fa fa-fw fa-trash-alt"></i></button>
          </form>
          </td>
        </tr>
      <?php endforeach ?>
      </table>
      <table class="table <?= $showReviews?> table-responsive-sm">
        <thead class="thead-dark">
        <th class="heading" colspan="4"><h4>Seznam recenzí</h4></th>
        <tr>
          <th>Název</th>
          <th>Ohodnocení</th>
          <th>Publikováno</th>
          <th>Akce</th>
        </tr>
      </thead>
        <tr>
          <?php foreach ($reviews as $review) : ?>
          <td><?= $review['title'] ?></td>
          <td><?= $review['average'] ?></td>
          <td><?= $review['published'] ?></td>
          <td>
            <form action="/profile" method="post">
              <input type="hidden" name="review_id" value="<?= $review['id'] ?>">
              <button type = "submit" name="publish" title="Změnit status publikace recenze"><i class="fa fa-fw fa-upload"></i></button>
              <button type = "submit" name="editReview" title="Editovat recenzi"><i class="fa fa-fw fa-edit"></i></button>
              <button type = "submit" name="deleteReview" title="Odstranit recenzi"><i class="fa fa-fw fa-trash-alt"></i></button>
            </form>
          </td>
        </tr>
      <?php endforeach ?>
      </table>
      <hr>
      <form action="/profile" method="post">
        <a href=/profile?newArticle class="btn btn-success">Vložit článek</a>
        <button class="btn btn-primary" type="submit" name="logout">Odhlásit se</button>
        <button class="btn btn-danger" type="submit" name="deleteACC">Zrušit účet</button>
      </form>
    </div>
  </div>
</body>

</html>
